app/flatui/js/jquery-ui-1.10.3.custom.min.js
app/flatui/js/jquery.ui.touch-punch.min.js
app/flatui/js/bootstrap.min.js
app/flatui/js/bootstrap-select.js
app/flatui/js/flatui-checkbox.js
app/flatui/js/bootstrap-switch.js
app/flatui/js/flatui-radio.js
app/flatui/js/jquery.tagsinput.js
app/flatui/js/jquery.placeholder.js
app/flatui/js/application.js
